# server:
#   port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MakMargam/spring-cloud-config-store
          search-paths:
           - '*service'



